# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoe',
            fields=[
                ('myid', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('modelname', models.CharField(max_length=200)),
                ('img1', models.ImageField(blank=True, null=True, upload_to=b'media/')),
                ('image_height', models.PositiveIntegerField(blank=True, default=b'100', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default=b'100', editable=False, null=True)),
            ],
        ),
    ]
