# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relations',
            fields=[
                ('relid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=200)),
                ('shoeid', models.PositiveIntegerField()),
            ],
        ),
    ]
