# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0002_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr',
            fields=[
                ('myid', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('modelname', models.CharField(max_length=200)),
            ],
        ),
    ]
