# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0003_usr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usr',
        ),
    ]
