# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0004_delete_usr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='relations',
            new_name='relation',
        ),
    ]
