# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0005_auto_20170902_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'K', b'Kids')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
