# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0006_shoe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
