# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0010_shoe_img3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='price',
        ),
        migrations.AddField(
            model_name='shoe',
            name='occasion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='outer_material',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='pack_of',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shoe',
            name='pack_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='sizes',
            field=models.CharField(choices=[(b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='weight',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
