# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0011_auto_20170926_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='sizes',
        ),
        migrations.AddField(
            model_name='shoe',
            name='size10',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoe',
            name='size6',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoe',
            name='size7',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoe',
            name='size8',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoe',
            name='size9',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
