# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0012_auto_20170926_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='size10',
            field=models.PositiveIntegerField(choices=[(1, b'Available'), (0, b'Unavailable')], default=0),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size6',
            field=models.PositiveIntegerField(choices=[(1, b'Available'), (0, b'Unavailable')], default=0),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size7',
            field=models.PositiveIntegerField(choices=[(1, b'Available'), (0, b'Unavailable')], default=0),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size8',
            field=models.PositiveIntegerField(choices=[(1, b'Available'), (0, b'Unavailable')], default=0),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size9',
            field=models.PositiveIntegerField(choices=[(1, b'Available'), (0, b'Unavailable')], default=0),
        ),
    ]
