# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0013_auto_20170926_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='pack_price',
            new_name='price',
        ),
    ]
