# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0014_auto_20170926_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
