# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0017_auto_20170926_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='neck_height',
            field=models.CharField(choices=[(b'Zero', b'Zero'), (b'Ankel', b'Ankel'), (b'Calf', b'Calf'), (b'Knee', b'Knee'), (b'Thigh', b'Thigh')], default=b'Ankel', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='floater',
            field=models.CharField(choices=[(b'shoe_boot', b'shoe_boot'), (b'shoe_oxford', b'shoe_oxford'), (b'shoe_loafer', b'shoe_loafer'), (b'shoe_sneaker', b'shoe_sneaker'), (b'shoe_sport', b'shoe_sport'), (b'shoe_boot', b'shoe_boot'), (b'slipper_beach', b'slipper_beach'), (b'slipper_glider', b'slipper_glider'), (b'slipper_printed', b'slipper_printed'), (b'sandal_mules', b'sandal_mules'), (b'sandal_glider', b'sandal_glider'), (b'sandal_opentoe', b'sandal_opentoe'), (b'sandal_closetoe', b'sandal_closetoe'), (b'sock_winter', b'sock_winter'), (b'sock_sport', b'sock_sport')], max_length=200),
        ),
    ]
