# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0019_auto_20170927_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('queryid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=1000)),
            ],
        ),
    ]
