# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoeshowroom', '0020_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='queryx',
        ),
    ]
