# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171025_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank_Details',
            new_name='Bank_Detail',
        ),
    ]
