# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171026_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank_Detail',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Chocolate',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Shipper',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
